-- Seed old curriculum subject: 수1
-- Run after 01_schema_update.sql and 02_reset_curriculum.sql.

BEGIN;

DO $$
DECLARE
  v_subject_id BIGINT;
  v_major_id BIGINT;
  v_middle_id BIGINT;
BEGIN
  INSERT INTO subjects (name, curriculum_type, order_index) VALUES ('수1', 'old', 1) RETURNING id INTO v_subject_id;
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '지수', 1) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '거듭제곱근', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱근1 (뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱근2 (실근듸 개수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱근3 (합답형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱근4 (성질과 계산)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱근의 활용1 (성질과 계산의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱근의 활용2 (대소 비교)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수의 확장과 지수법칙', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수법칙1 (정수지수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수법칙2 (유리수지수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수법칙3 (실수지수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱근의 성질 및 지수법칙 증명', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '식의 계산1 (대일)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '식의 계산2 (밑의 통일)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '식의 계산3 (치환)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '식의 계산4 (역수 관계의 활용)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '식의 계산5 (번분수식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '식의 계산6 (연립의 기술)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석과 추론', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수법칙의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (대소 비교)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (정수론)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (도형조건과 함수조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (실생활)', 4);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '로그', 2) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '로그의 정의', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 정의1 (정의)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 정의2 (로그가 정의될 조건)', 2);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '로그의 성질', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질1 (밑과 진수의 거듭제곱)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질2 (합과 차)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질3 (밑 변환)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질4 (지수에 로그)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질5 (문자로 나타내기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질6 (식의 값 구하기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질7 (합답형 및 증명)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질 활용1 (로그와 근과 계수의 관계)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질 활용2 (해석)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질 활용3 (도형)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질 활용4 (Mm)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질 활용5 (대소 비교)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질 활용6 (정수론)', 13);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그의 성질 활용7 (실생활)', 14);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '상용로그', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '상용로그1 (밑의 생략)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '상용로그2 (정수부분과 소수부분)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '상용로그3 (상용로그표의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '상용로그의 활용1 (근과 계수의 관계)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '상용로그의 활용2 (정수부분)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 활용1 (빼거나 더해서 정수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 활용2 (소수부분의 범위와 표현)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 활용3 (추론과 정수론)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 활용4 (실생활 활용)', 9);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '지수함수', 3) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수함수의 그래프', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수의 그래프1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수의 그래프2 (평행이동과 대칭이동)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수의 그래프3 (지수함수의 성질)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수의 그래프4 (평행이동과 넓이)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수의 그래프의 해석1 (기본)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수의 그래프의 해석2 (길이와 넓이)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수를 이용한 수의 대소 비교', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수함수의 최대와 최소', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm1 (기본그래프)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm2 (지수가 이차식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm3 (치환)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm4 (여러가지 Mm)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수방정식과 부등식', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수방정식1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수방정식2 (치환)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수방정식3 (연립방정식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수방정식4 (근과 계수의 관계)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수방정식5 (해석)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수부등식1 (기본)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수부등식2 (치환)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수부등식3 (연립부등식)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수부등식4 (해의 조건)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수함수의 활용', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (부등식과 그래프)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (지수방정식의 실근 조건, 치환)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (지수방정식의 실근 조건, 그래프로 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 부등식의 성립조건', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (그래프를 이용한 대소 비교)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (추론과 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (격자점 문제)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용8 (실생활 활용)', 8);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '로그함수', 4) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '로그함수의 그래프', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수의 그래프1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수의 그래프2 (평행이동과 대칭이동)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수의 그래프3 (로그함수의 성질)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수의 그래프4 (평행이동과 넓이)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수의 그래프의 해석1 (기본)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수의 그래프의 해석2 (길이와 넓이)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수를 이용한 수의 대소 비교', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '로그함수의 최대와 최소', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm1 (기본 그래프)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm2 (진수가 함수식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm3 (치환)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm4 (여러가지 Mm)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수함수와 로그함수의 역함수 관계', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수1 (역함수의 함숫값)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수2 (역함수 구하기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수3 (y=x 대칭)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수4 (y=x대칭의 발견)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수5 (원함수와 역함수의 교점)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '로그방정식과 부등식', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그방정식1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그방정식2 (치환)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그방정식3 (연립방정식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그방정식4 (근과 계수의 관계)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그방정식5 (해석)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그부등식1 (기본)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '초그부등식2 (치환)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그부등식3 (연립부등식)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그부등식4 (해의 조건)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그부등식5 (해석)', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '로그함수의 활용', 5) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (방, 부등식과 그래프)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (방정식의 실근 조건, 치환)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (로그방정식의 실근 조건, 그래프로 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (부등식의 성립조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (그래프를 이용한 대소비교)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (추론과 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (격자점 문제)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용8 (실생활 활용)', 8);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '삼각함수의 정의', 5) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '일반각과 호도법', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법1 (정의)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법2 (동경)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법3 (두 동경의 위치관계)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법4 (부채꼴)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법5 (부채꼴의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법6 (Mm)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법7 (원뿔)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반각과 호도법8 (추론과 해석)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 정의 및 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의1 (삼각함수의 뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의2 (삼각함수의 부호)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의3 (부호와 함수변형규칙)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의4 (특수각의 확장)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의5 (삼각함수 사이의 관계, 간단히 하기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의6 (삼각함수 사이의 관계, 값 구하기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (삼각함수의 정의)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (특수각의 확장)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (삼각함수 사이의 관계)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 해석', 10);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '삼각함수의 그래프', 6) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 그래프', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프1 (주기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프2 (기본 삼각함수의 그래프)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프3 (평행이동과 대칭이동)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프4 (표준형 그래프에서 Mm)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프5 (그래프의 성질)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프6 (그래프 조건)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프7 (대칭성)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프8 (대소비교)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 그래프 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '각 변형1 (각변형 규칙)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '각 변형2 (규칙성, 대칭성)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '각 변형3 (각 변형 규칙의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (대칭성과 길이 또는 넓이)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (그래프의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (치환을 이용한 Mm)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (여러가지 Mm)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각방정식과 부등식', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각방정식1 (일차식꼴)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각방정식2 (이차식꼴)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각방정식3 (교점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각방정식4 (대칭성과 실근)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각방정식5 (실근의 개수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각부등식1 (일차식꼴)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각부등식2 (이차식꼴)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방부등식의 활용1 (이차함수의 활용)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방부등식의 활용2 (부등식의 성립조건)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방부등식의 활용3 (여러가지)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방부등식의 활용4 (추론과 해석)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방부등식의 활용5 (실생활 활용)', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '삼각함수의 활용', 7) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '사인법칙과 코사인법칙', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사인법칙1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사인법칙2 (사인법칙의 변형)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '코사인법칙1 (기본)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '코사인법칙2 (코사인법칙의 변형)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사인법칙과 코사인법칙의 동시적용)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '사인법칙과 코사인법칙의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (삼각형의 모양)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (사인법칙의 활용)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (코사인법칙의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (사인법칙과 코사인법칙의 활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (식의 모양-연결공식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (Mm)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (실생활 활용)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각형의 넓이', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이1 (끼인각 공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이2 (끼인각 공식 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이3 (세 변의 길이)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이4 (내접원과 외접원)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이5 (사각형의 넓이)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이6 (각의 활용)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이7 (넓이관계식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이8 (포함과 배제)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이9 (Mm)', 9);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '등차수열', 8) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등차수열의 일반항', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 뜻 (일반항)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항1 (관계식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항2 (조건을 만족시키는 등차수열의 항)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항3 (두 수 사이에 수를 넣은 등차수열)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항4 (일반항의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항1 (등차중항)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항2 (등차중항을 이용한 간단한 계산)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항3 (중항의 활용)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항4 (등차수열을 이루는 수)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등차수열의 합', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합1 (합 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합2 (합으로 표현된 관계식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합3 (합에 대한 성질)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합4 (부등식의 해)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합5 (등차수열의 부분합)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합의 활용1 (합의 Mm)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합의 활용2 (함수, 도형 또는 실생활)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 합과 일반항 사이의 관계1 (기본)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 합과 일반항 사이의 관계2 (해석)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등차수열의 추론과 함수적 해석', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론1 (등차수열의 결합과 합성)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론2 (함수적 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론3 (추론과 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론4 (추론과 정수론)', 4);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '등비수열', 9) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등비수열의 일반항', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항1 (관계식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항2 (조건을 만족시키는 등비수열의 항)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항3 (두 수 사이에 수를 넣은 등비수열)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반항4 (등차수열과 등비수열)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항1 (등비중항)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항2 (등차중항과 등비중항)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항3 (등비중항의 활용)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중항4 (등비수열을 이루는 수)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등비수열의 합', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합1 (합 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합2 (합으로 표현된 관계식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합3 (부분합 수열)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합4 (부등식의 해)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합5 (합의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 합과 일반항 사이의 관계1 (기본)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 합과 일반항 사이의 관계2 (해석)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등비수열의 추론과 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론1 (등비수열의 결합과 합성)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론2 (정수론)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (도형과 함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (실생활)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (원리합계)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (상용로그)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '수열의합', 10) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '시그마의 뜻과 성질', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '시그마의 뜻1 (표현과 나열)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '시그마의 뜻2 (등차수열)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '시그마의 뜻3 (등비수열)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '시그마의 성질1 (기본성질)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '시그마의 성질2 (식 변형)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '자연수의 거듭제곱의 합', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자연수의 거듭제곱의 합1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자연수의 거듭제곱의 합2 (식 변형)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자연수의 거듭제곱의 합3 (시그마 변수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자연수의 거듭제곱의 합4 (지수 꼴의 일반항)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자연수의 거듭제곱의 합5 (나열된 수)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '여러가지 수열의 합', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '소거형1 (시그마의 성질)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '소거형2 (부분분수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '소거형3 (기타)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 수열1 (식의 모양)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 수열2 (멱급수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 수열3 (군수열)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 수열4 (계차수열)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '항등식과 수열, 활용', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식과 수열1 (합과 일반항의 관계)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식과 수열2 (주어진 일반항)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식과 수열3 (일반항 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (일반항 구하기, 대수와 식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (일반항 구하기, 함수와 도형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (추론, 주기수열)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (추론, 규칙적인 변화)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (여러가지 추론)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (격자점)', 9);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '수학적귀납법', 11) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '귀납적 정의', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식1 (등차수열)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식2 (등비수열)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식3 (이웃하는 항의 차가 f(n)꼴)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식4 (이웃하는 항의 몫이 f(n)꼴)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식5 (이웃하는 항이 일차관계식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식6 (이웃하는 세 항의 관계식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식7 (합이 포함된 점화식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식8 (분수꼴 점화식, 치환)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식9 (이웃하는 항의 합이 합 또는 곱으로 표현된 점화식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식10 (주기수열)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식11 (여러가지 점화식)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식12 (점화식 만들기', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점화식13 (일반항 추론)', 13);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '수학적 귀납법', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 귀납법1 (귀납법)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 귀납법2 (등식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 귀납법3 (부등식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 귀납법4 (정수론)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 귀납법5 (점화식)', 5);
END $$;

COMMIT;
