-- Seed old curriculum subject: 확률과통계
-- Run after 01_schema_update.sql and 02_reset_curriculum.sql.

BEGIN;

DO $$
DECLARE
  v_subject_id BIGINT;
  v_major_id BIGINT;
  v_middle_id BIGINT;
BEGIN
  INSERT INTO subjects (name, curriculum_type, order_index) VALUES ('확률과통계', 'old', 3) RETURNING id INTO v_subject_id;
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '여러가지순열', 1) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '중복순열', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열1 (기호와 뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열2 (중복허락, 선택)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열3 (선택 후 배열)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열4 (중복허락, 여사건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열5 (정수의 개수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열6 (함수의 개수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열7 (집합의 개수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복순열8 (추론)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합분할과 자연수분할', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '원순열', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원순열1 (원순열)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원순열2 (다각형)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원순열3 (색칠)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원순열4 (다면체)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원순열4 (추론)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '같은 것을 포함한 순열', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '같은 것을 포함한 순열1 (배열)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '같은 것을 포함한 순열2 (정해진 순서)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '같은 것을 포함한 순열3 (일부 선택 후 배열)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '같은 것을 포함한 순열4 (정수의 개수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '같은 것을 포함한 순열5 (함수의 개수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '같은 것을 포함한 순열6 (같은 것을 포함한 원순열)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '같은 것을 포함한 순열7 (점의 이동)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최단경로의 수1 (평면)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최단경로의 수2 (추론)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최단경로의 수3 (입체)', 10);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '중복조합', 2) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '중복조합', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합1 (기호와 뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합2 (기본적인 중복조합 적용)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합3 (개수조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합4 (전개식에서 항의 개수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합5 (부정방정식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합6 (함수의 개수)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '중복조합의 활용 (식 활용)', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합식 활용1 (배열에서 종류가 바뀌는 상황)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합식 활용2 (소인수분해)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합식 활용3 (부등식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합식 활용4 (부정방정식의 활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합식 활용5 (부등식을 방정식으로 동치변형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합식 활용6 (연립)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '중복조합식 활용7 (추론과 해석)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '이항정리', 3) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '특정항의 계수', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '특정항의 계수1 (기본형)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '특정항의 계수2 (분수꼴)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '특정항의 계수3 (곱의 꼴)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '특정항의 계수4 (합의 꼴)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '특정항의 계수5 (미분 또는 적분)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이항정리의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (이항정리를 이용한 수의 계산)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (이항정리를 이용한 나머지)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (파스칼의 삼각형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (이항계수의 성질)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (이항계수의 성질의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (이항계수의 곱)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '확률의 뜻과 활용', 4) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '시행과 사건', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '시행과 사건', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '배반사건1 (배반사건의 뜻)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '배반사건2 (배반사건이 될 조건)', 3);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '수학적 확률', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률1 (경우의 수 - 단순확률, 케이스 분류 포함)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률2 (순열 이용)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률3 (조합 이용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률4 (중복순열 이용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률5 (원순열 이용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률6 (같은 것이 있는 순열 이용)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률7 (중복조합 이용)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률8 (같은 것을 다른 것으로 보는 경우)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률9 (분할)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률10 (집합)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률11 (함수)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수학적 확률12 (확률의 성질)', 12);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '통계적 확률과 기하학적 확률', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '통계적 확률', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기하학적 확률', 2);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '확률의 덧셈정리', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리1 (확률의 계산)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리2 (배반사건이 아닌 경우)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리3 (배반사건인 경우)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여사건의 확률1 (기본. 적어도)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여사건의 확률2 (이상 또는 이하)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여사건의 확률3 (기타)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '조건부 확률', 5) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '조건부 확률의 뜻', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건부 확률의 뜻과 계산', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건부 확률의 뜻1 (표 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건부 확률의 뜻2 (문장 조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건부 확률의 뜻3 (경우의 수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건부 확률의 뜻4 (활용)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '조건부확률과 곱셈정리', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '종속인 사건의 곱셈정리1 (비복원추출)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '종속인 사건의 곱셈정리2 (상황별 확률의 변화)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '종속인 사건의 곱셈정리2 (확률조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈정리와 조건부확률1 (종속적 선후시행)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈정리와 조건부확률2 (동시시행)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈정리와 조건부확률3 (확률조건)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈정리와 조건부확률4 (경기)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '사건의 독립과 종속', 6) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '독립과 종속', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률의 계산 (독립일 때)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립과 종속1 (독립 또는 종속조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립과 종속2 (독립과 종속의 판정)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립과 종속3 (성질, 참거짓)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '독립인 사건의 곱셈정리', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립인 사건의 곱셈정리1 (확률조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립인 사건의 곱셈정리2 (확률구하기)', 2);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '독립시행의 확률', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립시행의 확률1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립시행의 확률2 (독립시행을 여러 번 - 곱셈정리)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립시행의 확률3 (여사건의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립시행의 확률4 (선승제)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립시행의 확률5 (경로문제)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립시행의 확률6 (조건부확률)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '독립시행의 확률7 (활용)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률과 점화식', 8);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '이산확률분포', 7) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이산확률변수', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이산확률분포의 성질1 (확률의 총합, 미정계수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이산확률분포의 성질2 (확률 구하기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률분포 구하기', 3);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이산확률변수의 평균과 표준편차', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균과 표준편차 (기본공식, 도수분포표)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균1 (표)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균2 (확률질량함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균3 (확률분포 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표준편차1 (표)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표준편차2 (확률질량함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표준편차3 (확률분포 구하기)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균과 표준편차 (빈 칸 넣기)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, 'aX+b의 평균과 표준편차', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 평균1 (공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 평균2 (표)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 평균3 (확률질량함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 평균4 (확률분포 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 표준편차1 (공식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 표준편차2 (표)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 표준편차3 (확률질량함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 표준편차4 (확률분포 구하기)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'X의 제곱의 평균1 (공식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'X의 제곱의 평균2 (활용)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'aX+b의 평균과 표준편차 (빈 칸 넣기)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이항분포', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포1 (확률)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포2 (평균과 분산의 공식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포3 (평균과 분산의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포4 (aX+b의 평균과 분산의 공식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포5 (aX+b의 평균과 분산의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포6 (X의 제곱의 평균)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포7 (시그마 표현의 해석)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포8 (지수꼴 확률변수)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포9 (큰 수의 법칙)', 9);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '정규분포', 8) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '확률밀도함수', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률밀도함수1 (성질)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률밀도함수2 (확률)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률밀도함수3 (함수의 대칭성 또는 주기성 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률밀도함수4 (활용)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정규분포의 확률밀도함수', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정규분포곡선1 (성질)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정규분포곡선2 (대칭성과 확률)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정규분포곡선3 (정규분포와 확률)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정규분포곡선4 (두 확률밀도함수의 관계)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정규분포의 표준화', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률 구하기1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률 구하기2 (실생활)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률 구하기3 (실생활. 곱셈정리)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률 구하기4 (실생활. 도수 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률관계식1 (변수 1개)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률관계식2 (변수2개)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률관계식3 (실생활)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률관계식4 (실생활. 커트라인 문제)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표준화를 이용한 비교', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '확률밀도함수의 해석', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이항분포와 정규분포의 관계', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포의 확률1 (정규분포화)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포의 확률2 (확률질량함수의 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포의 확률3 (실생활, 주어진 확률)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포의 확률4 (실생활. 수학적 확률을 계산하여 적용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포의 확률관계식1 (정규분포화)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이항분포의 확률관계식2 (실생활)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정규분포를 이용한 이항분포의 확률 구하기', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '통계적 추정', 9) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '모평균과 표본평균', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모평균과 표본평균1 (표본평균의 확률)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모평균과 표본평균2 (모집단의 분포와 표본평균의 분포의 관계)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모평균과 표본평균3 (모집단의 확률분포)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모평균과 표본평균4 (모집단의 확률분포 완성)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모평균과 표본평균5 (실생활에서 표본평균의 분포)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '표본평균의 정규분포', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표본평균의 정규분포1 (모집단의 정규분포)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표본평균의 정규분포2 (정규분포조건에서 확률)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표본평균의 정규분포3 (실생활, 확률 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표본평균의 정규분포4 (실생활, 확률조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '표본평균의 정규분포5 (실생활. 변수의 종합)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '모평균의 추정', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '신뢰구간1 (모표준편차)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '신뢰구간2 (표본표준편차)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '신뢰구간3 (관계식 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '신뢰구간4 (신뢰구간의 길이)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '신뢰구간5 (표본의 크기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '신뢰구간6 (미지수 신뢰도)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '신뢰구간7 (성질)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '모비율과 표본비율', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모비율1 (확률분포)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모비율2 (신뢰구간)', 2);
END $$;

COMMIT;
