-- Seed old curriculum subject: 미적분
-- Run after 01_schema_update.sql and 02_reset_curriculum.sql.

BEGIN;

DO $$
DECLARE
  v_subject_id BIGINT;
  v_major_id BIGINT;
  v_middle_id BIGINT;
BEGIN
  INSERT INTO subjects (name, curriculum_type, order_index) VALUES ('미적분', 'old', 4) RETURNING id INTO v_subject_id;
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '수열의 극한', 1) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '수열의 극한의 성질 및 계산', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산1 (무한대/무한대)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산2 (무한대-무한대)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산3 (무한대X0)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산4 (수열과 일반항)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한식의 해석1 (무한대/무한대)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한식의 해석2 (무한대-무한대)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한식의 해석3 (무한대X0)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 성질1 (수렴여부 판단)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 성질2 (극한의 분배)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 성질3 (극한식의 변형)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 성질4 (수열의 극한의 대소 관계)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등비수열의 극한의 성질 및 계산', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비수열의 극한의 수렴 조건', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산1 (기본 계산)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산2 (등비수열의 일반항)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산3 (등비수열의 합)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형의 계산4 (점화식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한식의 해석1 (부정형)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한식의 해석2 (공비가 미지수인 극한식의 계산)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한식의 해석3 (공비가 미지수인 극한식의 해석)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비수열의 극한의 성질1 (수렴)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비수열의 극한의 성질2 (대소 관계)', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '수열의 극한의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 극한의 활용1 (근호가 포함된 식의 정수부분과 소수부분)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 극한의 활용2 (대수 또는 방부등식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 극한의 활용3 (평면좌표 또는 함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 극한의 활용4 (원 관련)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 극한의 활용5 (도형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 극한의 활용6 (격자점)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비수열의 극한의 활용1 (대수 또는 방부등식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 및 도형', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한으로 정의된 함수1 (기본)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한으로 정의된 함수2 (연속성)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한으로 정의된 함수3 (미분과 적분)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '수열의 극한의 진위판정', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '급수', 2) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '급수의 성질 및 계산', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분합의 극한', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '급수의 성질', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '소거형 급수1 (분배 후 소거)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '소거형 급수2 (분수분리)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '소거형 급수3 (부분분수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '소거형 급수4 (로그와 약분)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '급수의 수렴과 발산1 (판단)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '급수의 수렴과 발산2 (수렴조건)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '등비급수의 성질 및 계산', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 수렴조건1 (공비의 범위)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 수렴조건2 (판단)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 계산1 (기본)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 계산2 (등비수열의 일반항)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 계산3 (삼각함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 계산4 (주기수열)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 계산5 (합의 해석)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 계산6 (순환소수)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '급수의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '급수의 진위판정', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반급수의 활용1 (대수 및 방부등식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일반급수의 활용2 (함수 및 도형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 활용1 (대수 및 방부등식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 활용2 (함수 및 도형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 활용3 (실생활)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수의 활용4 (급수로 정의된 함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수와 도형1 (좌표)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수와 도형2 (길이)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수와 도형3 (넓이)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '등비급수와 도형4 (프랙탈)', 11);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '지수, 로그함수의 미분', 3) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '자연상수 e의 정의', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e의 정의1 (무한소)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e의 정의2 (무한대)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e의 정의3 (특정값)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e를 포함한 지수함수와 로그함수의 계산', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수, 로그함수의 극한', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 기본계산1 (지수함수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 기본계산2 (로그함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 기본해석 (지수의 밑이 미지수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e를 포함한 극한의 계산1 (로그식. 무한소)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e를 포함한 극한의 계산2 (로그식. 치환)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e를 포함한 극한의 계산3 (지수식. 무한소)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e를 포함한 극한의 계산4 (지수식. 치환)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e를 포함한 극한의 해석1 (미정계수 결정)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'e를 포함한 극한의 해석2 (극한의 성질 활용)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 활용1 (e 또는 e의 정의 관련)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 활용2 (지수식 극한)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 활용3 (로그식 극한)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수로그함수의 연속성', 13);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '지수, 로그함수의 도함수', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식1 (지수함수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식2 (로그함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석1 (극한값 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석2 (극한식의 해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석3 (함수의 해석)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석4 (미분가능성)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '삼각함수의 덧셈정리', 4) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 정의', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의1 (역수 관계)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의2 (삼각함수 사이의 관계)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의3 (삼각방정식과 삼각부등식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의4 (해석 및 활용)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 덧셈정리', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리1 (사인과 코사인)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리2 (탄젠트)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리3 (덧셈정리의 역)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리4 (역함수의 함수값)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리5 (삼각함수의 합성)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리6 (배각공식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리7 (반각 공식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '덧셈정리8 (곱을 합 또는 차, 합 또는 차를 곱으로)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 해석 및 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용1 (각 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용2 (방정식 또는 부등식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용3 (수열)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용4 (삼각함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용5 (두 직선이 이루는 각)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용6 (다각형의 성질)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용7 (원의 성질)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용8 (삼각함수의 합성의 활용)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용9 (배각, 반각공식의 활용)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석 및 활용10 (복소평면)', 10);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '삼각함수의 미분', 5) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 극한', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 계산1 (기본 삼각함수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 계산2 (사인 또는 탄젠트)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 계산3 (식의 변형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 계산4 (코사인)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 계산4 (치환)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 계산5 (혼합계산)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 계산6 (성질)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '극한의 해석 및 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석1 (극한식의 해석)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석2 (연속성)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (함수의 그래프)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (다각형의 성질)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (원의 방정식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (원과 도형)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (두 개 이상의 원 또는 부채꼴의 관계)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼각함수의 도함수', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식1 (도함수의 정의)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식1 (기본공식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석1 (극한값 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석2 (극한식의 해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석3 (함수의 해석)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석4 (미분가능성)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건해석5 (정의된 함수)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '여러 가지 함수의 미분법', 6) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '몫의 미분법', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '몫의 미분법1 (기본 공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '몫의 미분법2 (극한값 구하기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '몫의 미분법3 (극한식의 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '몫의 미분법4 (x의 a제곱꼴)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '몫의 미분법5 (활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '몫의 미분법6 (함수 구하기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '몫의 미분법7 (연속성과 미분가능성)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '합성함수의 미분법', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수 미분법1 (미분계수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 미분법2 (극한값 구하기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 미분법3 (극한식의 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 미분법4 (활용)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '초월함수의 미분법', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각함수1 (공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각함수2 (해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각함수3 (활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼각함수4 (함수 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수1 (공식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수2 (해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수3 (활용)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '지수함수4 (함수 구하기)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수1 (공식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수2 (해석)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수3 (활용)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그함수4 (함수 구하기)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '초월함수의 미분가능성', 13);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '로그미분법', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그미분법1 (복잡한 분수식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '로그미분법2 (밑과 지수가 모두 변수)', 2);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '여러 가지 미분법', 7) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '매개변수 미분법', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '매개변수로 주어진 함수', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '매개변수 미분법1 (공식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '매개변수 미분법2 (해석 및 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '매개변수 미분법3 (함수 구하기)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '음함수 미분법', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '음함수의 미분법1 (공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '음함수의 미분법2 (활용)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '음함수의 미분법3 (정의된 함수)', 3);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '역함수 미분법', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 미분법1 (공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 미분법2 (결합 또는 합성함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 미분법3 (해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 미분법4 (활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 미분법5 (함수 구하기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 미분법6 (미분가능성)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이계도함수', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이계도함수1 (공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이계도함수2 (해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이계도함수3 (활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이계도함수4 (정의된 함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이계도함수5 (미분가능성)', 5);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '접선의 방정식', 8) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '접선의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접점 이용1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접점 이용2 (매개변수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접점 이용3 (음함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접점 이용4 (역함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기울기 이용1 (기본)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기울기 이용2 (매개변수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선 밖의 점 이용1 (기본)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선 밖의 점 이용2 (매개변수)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '접선의 방정식의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (두 직선이 이루는 각의 크기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (공통접선)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (접선의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (Mm)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (정의된 함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (평균값의 정리)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '극대, 극소와 최대, 최소', 9) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '증가와 감소, 극대와 극소', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소1 (증가 또는 감소하는 구간)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소2 (조건 해석, 실수 전체)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소3 (조건 해석, 제한 범위)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소1 (극값 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소2 (해석)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소3 (극값의 존재성)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소4 (불연속함수 또는 구간정의함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소5 (활용)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '곡선의 개형과 변곡점', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 개형1 (오목과 볼록)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 개형2 (오목 또는 볼록일 조건 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 개형3 (변곡점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 개형4 (변곡점의 해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 개형5 (변곡점과 접선)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 개형6 (변곡점의 존재성)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 개형7 (활용)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '그래프의 개형', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프의 개형1 (그래프 그리기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프의 개형2 (그래프 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프의 개형3 (주어진 함수의 해석. 참거짓 및 합답형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프의 개형4 (조건 해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프의 개형5 (함수 구하기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '그래프의 개형6 (정의된 함수)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '최대와 최소', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm1 (Mm 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm2 (Mm조건 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm3 (치환)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm4 (함수 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm5 (정의된 함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm6 (활용)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '방부등식에의 활용과 평면운동', 10) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '방정식과 미분', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분1 (실근의 개수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분2 (실근의 개수. 제한범위)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분3 (동치변형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분4 (활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분5 (함수 구하기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분6 (실근 또는 교점의 개수로 정의된 함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분7 (기타 정의된 함수)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '부등식과 미분', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분 (실수 전체)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분2 (제한 범위)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분3 (동치변형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분4 (활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분5 (대소 비교 및 증명)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '속도와 가속도', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선 운동', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면 운동1 (속도와 가속도)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면 운동2 (속도, 가속도의 크기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면 운동3 (속도, 가속도의 크기의 Mm)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면운동4 (점의 자취)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면운동5 (변화율)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '부정적분', 11) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '여러 가지 함수의 부정적분', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수1 (x의 n제곱)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수2 (부분분수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수3 (지수함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수4 (삼각함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수5 (구간정의함수)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '치환적분과 부분적분', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분1 (다항식 치환)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분2 (삼각함수 치환)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분3 (로그 치환)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분4 (지수치환)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분5 (여러 가지 치환)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분적분1 (한 번 적용)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분적분2 (중복 적용)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분적분3 (로그함수)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분과 부분적분', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '부정적분의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기1 (부정적분의 정의)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기2 (미분과 적분)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기3 (미분법의 역)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기4 (이변수 항등식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기5 (식변형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (함수의 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (연속성과 미분가능성)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (극대와 극소)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (최대와 최소)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (실생활)', 10);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '정적분', 12) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '여러 가지 함수의 정적분', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수1 (x의 n제곱)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수2 (지수함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수3 (삼각함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수4 (구간정의함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러 가지 함수5 (조건항등식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수6 (곱의 미분법의 역)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수7 (활용)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '치환적분과 부분적분', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분1 (유무리식 치환)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분2 (지수로그식의 치환적분)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분3 (삼각함수식의 치환적분)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분4 (구간정의함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분5 (삼각치환과 대칭적분)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분적분1 (기본)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분적분2 (구간정의함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '치환적분과 부분적분의 동시적용', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '우함수와 기함수', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '치환적분과 부분적분의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (적분식의 해석)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (적분식의 모양 변경)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (함수 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (정의된 함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (그래프 추론)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분으로 정의된 함수', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분으로 정의된 함수1 (정적분 전체 치환)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분으로 정의된 함수2 (적분함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분으로 정의된 함수3 (피적분함수의 변수와 상수의 구분)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (극한)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (적분식의 모양 변경)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (도함수의 활용)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (함수 구하기)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (정의된 함수)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (추론과 해석)', 9);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '정적분의 활용', 13) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분과 급수', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구분구적법', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 급수1 (다항함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 급수2 (초월함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 급수3 (나열된 항)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 급수4 (활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 급수5 (함수에서 식 세우기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 급수6 (도형에서 식 세우기)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분과 넓이', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이1 (그래프 조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이2 (그래프 그리기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이3 (대칭성)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이4 (함수 결정 후 넓이)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이5 (곡선과 접선으로 둘러싸인 도형의 넓이)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이6 (y축 기준)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분과 넓이의 해석', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석1 (넓이조건과 관계식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석2 (넓이가 같을 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석3 (넓이로 정의된 함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석4 (포함과 배제)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석5 (활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수와 정적분1 (대칭성)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수와 정적분2 (정적분과 급수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수와 정적분3 (함수 구하기)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분과 부피', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부피1 (좌표평면과 함수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부피2 (일반도형)', 2);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '평면운동과 곡선의 길이', 5) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선운동1 (위치. 위치 조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선운동2 (이동거리)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면운동1 (위치와 이동거리)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면운동2 (매개변수 함수 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 길이1 (매개변수로 주어진 함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 길이2 (y=f(x)꼴 함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선의 길이3 (해석 및 활용)', 7);
END $$;

COMMIT;
