-- Seed new curriculum subject: 공수1
-- Run after 01_schema_update.sql and 02_reset_curriculum.sql.

BEGIN;

DO $$
DECLARE
  v_subject_id BIGINT;
  v_major_id BIGINT;
  v_middle_id BIGINT;
BEGIN
  INSERT INTO subjects (name, curriculum_type, order_index) VALUES ('공수1', 'new', 6) RETURNING id INTO v_subject_id;
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '다항식의 연산', 1) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '용어와 의미', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '용어와 의미', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 용어와 식의 정리', 2);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '다항식의 덧셈과 뺄셈', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 덧셈과 뺄셈1 (주어진 다항식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 덧셈과 뺄셈2 (연립)', 2);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '다항식의 곱셈', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 곱셈1 (특정항의 계수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 곱셈2 (곱셈공식을 이용한 다항식의 전개)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 곱셈3 (공통부분이 있는 다항식의 전개)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 곱셈4 (식의 값 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈공식의 변형1 (문자 2개)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈공식의 변형2 (역수관계)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈공식의 변형3 (문자 3개, 제곱의 합)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈공식의 변형4 (문자 3개, 세제곱의 합)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곱셈공식의 변형5 (문자 3개, 차의 제곱의 합)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 곱셈의 활용1 (곱셈공식을 이용한 수의 계산)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 곱셈의 활용2 (도형 및 기타)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 곱셈의 활용3 (곱셈공식의 변형의 활용)', 12);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '다항식의 나눗셈', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 나눗셈1 (몫과 나머지)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 나눗셈2 (몫과 나머지의 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 나눗셈3 (몫과 나머지의 변형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 나눗셈4 (차수 낮추기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '다항식의 나눗셈의 활용', 5);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '항등식과 나머지정리', 2) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '항등식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식1 (계수비교법)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식2 (수치대입법)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식3 (여러 문자)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식4 (다항식의 나눗셈과 항등식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식5 (다항식의 계수의 합)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식6 (다항식 구하기)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '나머지정리', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '나머지정리1 (일차식으로 나눈 나머지)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '나머지정리2 (일차로 나눈 나머지+다항식의 변형)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식 세우기1 (일차식으로 나눈 나머지)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식 세우기2 (이차 이상으로 나눈 나머지)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식 세우기3 (이차 이상으로 나눈 나머지+다항식의 변형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식 세우기4 (몫을 나눈 나머지)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식 세우기5 (식의 변형)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식 세우기6 (다항식 구하기)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등식 세우기7 (차수 결정 후 다항식 구하기)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (수의 나눗셈과 나머지정리)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (인수정리)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (도형 및 실생활 활용)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (정수 분류)', 13);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '조립제법', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조립제법1 (일차식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조립제법2 (중복 적용)', 2);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '인수분해', 3) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '인수분해 기본', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해1 (기본 공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해2 (공식의 중복 적용)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해3 (공통부분 치환)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해4 (복이차식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해5 (여러 문자)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해6 (계수가 대칭인 식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해7 (특수한 식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해8 (종합)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해9 (인수정리)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '인수분해의 해석 및 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 해석1 (이차식이 정수범위에서 인수분해될 조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 해석2 (완전제곱꼴로 인수분해)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 해석3 (일차식의 곱으로 인수분해)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 해석4 (정수론)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 해석5 (공통인수를 가질 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 해석6 (두 다항식의 결정)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 해석7 (추론과 해석)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 활용1 (삼각형의 모양 판단)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 활용2 (수의 계산)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 활용3 (도형)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 활용4 (다항식의 최대공약수)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '인수분해의 활용5 (다항식의 최소공배수)', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '복소수', 4) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '복소수의 연산', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '복소수의 뜻', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '복소수의 연산1 (사칙연산)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '복소수의 연산2 (식의 값 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석1 (복소수가 서로 같을 조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석2 (복소수가 실수 또는 순허수가 될 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석3 (허수를 이용한 나머지정리)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '켤레복소수', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '켤레복소수의 연산1 (뜻과 연산)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '켤레복소수의 연산2 (조건을 만족하는 복소수 구하기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '켤레복소수의 성질1 (성질을 이용한 연산)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '켤레복소수의 성질2 (합답형)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '켤레복소수의 해석1 (연산한 값이 실수 또는 순허수인지 판단)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '켤레복소수의 해석2 (관계식의 의미 해석)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '복소수의 거듭제곱', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱1 (허수단위 i)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱2 (제곱한 값이 순허수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱3 (세제곱한 값이 실수 또는 순허수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거듭제곱4 (실수, 허수부분이 대칭인 분수꼴 복소수)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '음수제곱근', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '음수제곱근1 (계산)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '음수제곱근2 (해석)', 2);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '이차방정식', 5) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이차방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일차방정식의 해', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 해1 (풀기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 해2 (근대입)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 활용1 (복소수 범위에서 인수분해)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 활용2 (도형 및 기타)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 활용3 (실생활)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 활용4 (추론과 해석)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이차방정식의 판별식', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 근의 판별1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차방정식의 근의 판별2 (관계식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근의 판별의 활용1 (이차식이 완전제곱식이 될 조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근의 판별의 활용2 (두 일차식의 곱으로 인수분해될 조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근의 판별의 활용3 (추론과 해석)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이차방정식의 근과 계수의 관계', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계1 (두 근의 합과 곱)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계2 (관계식 처리)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계3 (켤레근)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계4 (근대입)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계5 (근에 대한 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계6 (실근의 부호)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계7 (이차방정식의 작성)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계의 활용1 (합성근)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계의 활용2 (잘못 보고 구한 근)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계의 활용3 (인수정리. 함수식 구하기)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계의 활용4 (도형)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '근과 계수의 관계의 활용5 (추론과 해석)', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '이차함수와 이차방정식', 6) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이차함수의 해석', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석1 (교점. 이차함수와 x축)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석2 (교점. 이차함수와 직선)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석3 (교점. 이차함수와 이차함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석4 (위치 관계. 이차함수와 x축)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석5 (위치 관계. 이차함수와 직선)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석6 (위치 관계. 이차함수와 이차함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본 활용1 (접선의 방정식 구하기)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본활용2 (위치관계에서 항등식 조건)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본 활용3 (도형)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본 활용4 (이차함수 구하기)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본 활용5 (기본 해석)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이차함수의 최대와 최소', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm1 (실수 전체)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm2 (제한 범위)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm3 (관계식 조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm4 (치환)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm5 (케이스 분류)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm6 (이차함수 구하기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm7 (최댓값 또는 최솟값으로 정의된 함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm8 (활용)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차함수의 Mm9 (실생활 활용)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '변수가 2개 이상인 이차식의 Mm', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이차함수의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (이차함수와의 교점의 개수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (절댓값 또는 가우스함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (구간정의함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (근의 분리)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (추론과 해석)', 5);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '여러가지방정식', 7) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼차방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식 풀기', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석1 (근대입 관계식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석2 (근과 계수의 관계)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석3 (켤레근)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석4 (근과 계수의 관계의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석5 (삼차방정식의 작성)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석6 (삼차식의 작성, 인수정리)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석7 (근의 판별)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼차방정식의 해석8 (관계식을 이용한 방정식 만들기)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '오메가의 성질1 (기본 성질)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '오메가의 성질2 (응용 및 활용)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '사차방정식', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식 풀기1 (인수정리와 인수분해)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식 풀기2 (치환과 인수분해)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식 풀기3 (복이차방정식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식 풀기4 (계수가 대칭인 방정식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식의 해석1 (근대입 관계식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식의 해석2 (근의 판별)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식의 해석3 (고차방정식의 근과 계수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사차 이상의 방정식의 해석4 (다항식 또는 방정식 구하기)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '고차방정식의 활용', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '연립방정식', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립방정식 풀기1 (일차와 이차)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립방정식 풀기2 (이차와 이차)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립방정식 풀기3 (대칭형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립방정식의 해석1 (공통해를 갖는 두 연립방정식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립방정식의 해석2 (해의 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립방정식의 활용', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정방정식', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '공통근을 가질 조건', 8);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '부등식', 8) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '일차부등식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식의 성질', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식 풀기1 (일차부등식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식 풀기2 (연립일차부등식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일차 또는 연립일차부등식의 해석1 (해가 주어진 경우)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일차 또는 연립일차부등식의 해석2 (해에 대한 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '절댓값을 포함한 부등식 풀기1 (일차부등식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '절댓값을 포함한 부등식 풀기2 (연립일차부등식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '절댓값을 포함한 일차부등식의 해석1 (해가 주어진 경우)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '절댓값을 포함한 일차부등식의 해석2 (해에 대한 조건)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 해석', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '일차부등식의 활용', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이차부등식', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식 풀기1 (이차부등식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식 풀기2 (연립이차부등식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식 풀기3 (절댓값 또는 가우스 포함)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 해석1 (부등식 세우기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 해석2 (해가 주어진 경우)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 해석3 (해에 대한 조건)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 해석4 (합성부등식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 해석5 (그래프의 위치 관계와 부등식)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 해석6 (항상 성립하는 부등식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 해석7 (해의 존재성)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립이차부등식의 해석1 (해가 주어진 경우)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립이차부등식의 해석2 (해의 조건)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연립이차부등식의 해석3 (그래프의 위치 관계)', 13);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 해석', 14);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차부등식의 활용', 15);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '고차부등식', 16);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '방정식에의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (이차방정식의 판별식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (연립방정식의 해의 존재성)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (이차방정식의 실근의 부호)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (이차방정식의 근의 분리)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (제한범위에서 항상 성립하는 이차부등식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (고차방정식의 근의 판별)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '순열과 조합', 9) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '합의 법칙과 곱의 법칙', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형1 (합의 법칙)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형2 (곱의 법칙)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형3 (기준 정하여 일일이 세기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형4 (지불방법과 지불금액)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형5 (완전순열)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준1 (자리를 기준)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준2 (자리를 기준, 색칠하기)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준3 (대상을 기준)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준4 (일부를 선택하는 케이스)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 이해', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '순열', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형1 (기호와 뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형2 (기본상황)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형3 (이웃하거나 이웃하지 않는 경우)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형4 (사전식 배열)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준1 (자리를 기준)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준2 (대상을 기준)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준3 (일부를 선택하는 케이스)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준4 (여사건)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포함과 배제', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 이해', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '조합', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형1 (기호와 뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형2 (기본상황)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형3 (뽑아서 나열)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기본유형4 (자동배열)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준1 (자리를 기준)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준2 (대상을 기준)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준3 (일부를 선택하는 케이스)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준4 (개수로 분류)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기준5 (여사건)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분할과 분배1 (분할)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분할과 분배2 (분배)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분할과 분배3 (활용, 토너먼트)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 이해', 13);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정수론과 경우의 수', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정수분류법1 (합에 대한 배수 조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정수분류법2 (소인수 기준)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정수분류법3 (합, 곱이 홀수 또는 짝수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정수분류법4 (나머지)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '배수판정법', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '약수의 개수', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대공약수와 최소공배수', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '순열과 조합의 활용', 5) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (직선의 개수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (삼각형의 개수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (사각형의 개수)', 3);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '행렬', 10) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '행렬의 뜻과 기본 연산', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '뜻과 연산1 (행렬의 뜻과 성분)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '뜻과 연산2 (두 행렬이 서로 같을 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '뜻과 연산3 (행렬의 덧셈, 뺄셈, 실수배)', 3);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '행렬의 곱셈', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈2 (행렬의 거듭제곱)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈3 (곱셈에 대한 성질)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈4 (교환법칙이 성립하는 경우)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈5 (행렬의 변형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈6 (단위행렬을 포함한 식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈7 (케일리-해밀턴 정리)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬의 곱셈8 (행렬 구하기)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '행렬의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (정의된 행렬)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (행렬의 추정)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (뜻과 연산의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (행렬의 곱셈의 활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (진위판정)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '역행렬', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역행렬1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '행렬과 그래프', 2);
END $$;

COMMIT;
