-- Seed new curriculum subject: 공수2
-- Run after 01_schema_update.sql and 02_reset_curriculum.sql.

BEGIN;

DO $$
DECLARE
  v_subject_id BIGINT;
  v_major_id BIGINT;
  v_middle_id BIGINT;
BEGIN
  INSERT INTO subjects (name, curriculum_type, order_index) VALUES ('공수2', 'new', 7) RETURNING id INTO v_subject_id;
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '평면좌표', 1) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '두 점 사이의 거리', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 점 사이의 거리1 (수직선)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 점 사이의 거리2 (좌표평면)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 점 사이의 거리의 활용1 (같은 거리에 있는 점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 점 사이의 거리의 활용2 (삼각형의 모양 조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 점 사이의 거리의 활용3 (삼각형의 모양판단)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '세 점 사이의 거리의 활용 (외심, 같은 거리)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '실생활 활용', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '내분점', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점1 (분점)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점2 (분점의 위치)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점3 (무게중심)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점4 (같은 비의 분점으로 이루어진 삼각형의 무게중심)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점5 (삼각형 관련정리)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점6 (사각형 관련정리)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점7 (추론과 해석)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내분점8 (실생활 활용)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '평면좌표의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (제곱의 합의 Mm)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (거리의 합 또는 차의 Mm)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (대소 비교)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (좌표화)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (중선의 정리)', 5);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '직선의 방정식', 2) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '직선의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식 (기울기 또는 절편 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식 세우기1 (기울기와 한 점)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식 세우기2 (지나는 두 점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식 세우기3 (절편)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석1 (직선의 개형과 계수의 부호)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석2 (세 점이 한 직선 위에 있을 조건)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석3 (직선으로 둘러싸인 도형의 넓이)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석4 (넓이 분할)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석5 (두 직선의 위치 관계)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석6 (평행 또는 수직조건이 주어진 직선)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석7 (수직이등분선)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석8 (세 직선의 위치 관계)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석9 (Mm)', 13);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석10 (정점을 지나는 직선)', 14);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 해석11 (정점을 지나는 직선의 활용)', 15);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '점과 직선 사이의 거리', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점과 직선 사이의 거리1 (공식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점과 직선 사이의 거리2 (거리 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점과 직선 사이의 거리3 (평행한 두 직선)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점과 직선 사이의 거리4 (삼각형의 넓이)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점과 직선 사이의 거리5 (해석)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점과 직선 사이의 거리6 (Mm)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '직선의 방정식의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (자취의 방정식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (추론 및 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (격자점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (실생활)', 4);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '원의 방정식', 3) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '원의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원의 방정식의 표준형1 (중심 또는 반지름 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원의 방정식의 표준형2 (해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원의 방정식 세우기1 (중심과 반지름)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원의 방정식 세우기2 (지름의 양 끝점)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원의 방정식 세우기3 (지나는 세 점)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원의 방정식 세우기4 (지나는 두 점)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원이 되기 위한 조건', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원과 축의 위치 관계1 (기본)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원과 축의 위치 관계2 (한 축에 접하는 원의 방정식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원과 축의 위치 관계3 (두 축에 접하는 원의 방정식)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 해석', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '실생활 활용', 12);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '위치 관계', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 원의 위치 관계1 (교점의 개수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 원의 위치 관계2 (두 원의 교점을 지나는 원의 방정식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '두 원의 위치 관계3 (공통현)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원과 직선의 위치 관계1 (교점의 개수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원과 직선의 위치 관계2 (원과 현)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원과 직선의 위치 관계3 (원과 접선)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원과 직선의 위치 관계4 (추론과 해석)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm1 (원과의 위치 관계 해석)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm2 (관계식의 해석)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '실생활 활용', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '접선의 방정식', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접선의 방정식1 (접점)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접선의 방정식2 (기울기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접선의 방정식3 (원 밖의 점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접선의 방정식4 (공통접선)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '자취의 방정식', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자취의 방정식1 (아폴로니우스의 원)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자취의 방정식2 (일반)', 2);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '도형의 이동', 4) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '평행이동과 대칭이동', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평행이동1 (점)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평행이동2 (직선 또는 이차함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평행이동3 (원)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '대칭이동1 (점)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '대칭이동2 (직선 또는 이차함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '대칭이동3 (원)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평행이동과 대칭이동1 (점)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평행이동과 대칭이동2 (도형)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '축에 평행한 직선에 대한 대칭이동', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '점에 대한 대칭이동', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선에 대한 대칭이동', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '이동의 해석과 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용1 (절댓값함수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용2 (이동의 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용3 (Mm, 축 또는 직선)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용4 (Mm, 일반 직선)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용5 (Mm, 원 위의 점)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용6 (Mm, 거리차)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용7 (Mm. 도형)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용8 (Mm, 실생활)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용9 (추론과 규칙성)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이동의 해석과 활용10 (해석과 추론)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식의 영역', 11);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '집합의 뜻', 5) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '집합과 원소', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 뜻', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기호와 의미1 (집합과 원소 사이의 관계)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기호와 의미2 (집합의 표현 방법)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기호와 의미3 (원소의 개수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기호와 의미4 (집합 사이의 포함 관계)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기호와 의미5 (집합을 원소로 가지는 집합)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기호와 의미6 (서로 같은 집합)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 활용1 (방정식)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 활용2 (부등식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 활용3 (행렬)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 활용4 (순열과 조합)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '항등원과 역원', 12);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '부분집합', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분집합1 (부분집합 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분집합2 (개수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분집합3 (개수, 원소의 개수 조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분집합3 (개수, 집합의 포함 관계)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '추론과 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 해석', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 케이스', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론과 정수론', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부분집합의 개수와 추론', 4);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '집합의 연산', 6) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '집합의 연산자', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합연산자1 (기본 의미)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합연산자2 (서로소)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합연산자3 (다중연산)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합연산자4 (원소배치해석)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '집합의 연산법칙', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙1 (기본 법칙)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙2 (복합사용)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙3 (벤다이어그램)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙4 (원소 구하기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙5 (포함 관계)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙6 (원소배치해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙7 (정의된 연산)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연산법칙8 (합답형, 옳은 것 찾기)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '집합의 연산의 해석과 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 개수1 (원소배치해석)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 개수2 (원소의 개수 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '원소배치해석 (원소의 개수 조건, 모든 원소의 합 또는 곱)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 연산의 해석 및 활용1 (복소수의 연산 및 방정식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 연산의 해석 및 활용2 (위치 관계)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 연산의 해석 및 활용3 (부등식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '집합의 연산의 해석 및 활용4 (순열과 조합)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론1 (기본)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론2 (집합의 연산법칙)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론3 (정수론)', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '유한집합의 원소의 개수', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유한집합의 원소의 개수1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유한집합의 원소의 개수2 (약수와 배수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유한집합의 원소의 개수3 (활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유한집합의 원소의 개수4 (Mm)', 4);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '명제의 형식', 7) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '모든, 어떤 명제', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '조건과 명제의 뜻과 참거짓', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '명제와 조건의 부정', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '진리집합', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모든, 어떤 명제1 (참, 거짓)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모든, 어떤 명제2 (모든 - 참일 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모든, 어떤 명제3 (어떤 - 참일 조건)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모든, 어떤 명제4 (거짓일 조건)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모든, 어떤 명제5 (명제의 부정)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '모든, 어떤 명제6 (원명제와 부정명제의 관계)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, 'pq명제', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제1 (참, 거짓 판별)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제2 (반례)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제3 (명제의 참거짓과 진리집합의 포함 관계)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제4 (명제가 참일 조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제5 (명제가 거짓일 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제6 (추론)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제의 변형1 (역, 대우)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제의 변형2 (역, 대우의 참, 거짓 판별)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제의 변형3 (명제가 참일 조건)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'pq명제의 변형4 (삼단논법)', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '필요조건과 충분조건', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '필요조건과 충분조건1 (판단)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '필요조건과 충분조건2 (조건 찾기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '필요조건과 충분조건3 (삼단논법)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '필요조건과 충분조건4 (해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '필요조건과 충분조건5 (추론과 활용)', 5);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '명제의 증명', 8) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '명제의 증명법', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증명1 (직접 증명)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증명2 (귀류법)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증명3 (대우를 이용한 증명)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증명4 (문장에서 추론)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '절대부등식', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '절대부등식1 (판단)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '절대부등식1 (증명)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '절대부등식2 (성립조건)', 3);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '절대부등식을 이용한 최대, 최소', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm1 (산술기하)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm2 (산술기하와 식변형)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm3 (산술기하의 활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm4 (코시-슈바르츠 부등식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm5 (코시-슈바르츠 부등식의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, 'Mm6 (기타)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '함수의 정의', 9) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '함수의 뜻', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 뜻1 (함숫값)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 뜻2 (치역)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 뜻3 (함수가 정의될 조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 뜻4 (서로 같은 함수)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '함수의 종류', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 종류1 (뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 종류2 (함숫값 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 종류3 (항등함수 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 종류4 (일대일대응일 조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 종류5 (추론)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '함수와 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (조건항등식, 적절한 대입)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (조건항등식, 항등식의 변형)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (조건항등식, 고정 또는 값 구하기, 기하적 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (방정식의 실근)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (함수가 이루는 도형의 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (최대, 최소)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (추론)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용8 (실생활)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용9 (자취의 방정식)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 개수1 (기본)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 개수2 (제한 조건)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수의 개수3 (추론과 케이스)', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '합성함수와 역함수', 10) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '합성함수', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 함숫값1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 함숫값2 (구간정의 함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 함숫값3 (성질활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 함숫값4 (추론)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수 구하기', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 조건 해석1 (합성함수가 정의될 조건)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 조건 해석2 (교환법칙이 성립할 조건)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수의 성질', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기1 (껍질함수)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기2 (알맹이 함수)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기3 (미정계수법)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '합성함수의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (최대, 최소)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (합성하기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (추론)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (함수의 개수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (실생활 활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수와 방정식1 (합성함수 구하기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수와 방정식2 (치환)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '합성함수와 부등식', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '역함수', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 함숫값1 (역대응)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 함숫값2 (기본성질)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 함숫값3 (역함수와 합성)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수 구하기', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 성질1 (기본성질)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 성질2 (항등식의 변형)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 성질3 (f((ax+b)꼴 함수의 역함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수의 성질4 (합답형)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '역함수의 활용', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석1 (함수의 기본상황)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석2 (역함수가 존재할 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석3 (항등식 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석4 (y=x의 활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (추론)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (함수의 개수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (문자2개 항등식)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '유리식과 유리함수', 11) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '유리식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분수식1 (기본 계산)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분수식2 (번분수와 부분분수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분수식3 (식의 정리)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분수식4 (정수론)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분수식5 (활용)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '유리함수', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석2 (점근선 또는 지나는 점)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석3 (그래프 조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석4 (대칭성)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석5 (이동의 해석)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석6 (지나는 사분면)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석7 (성질, 합답형)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석8 (함수의 Mm)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석9 (위치 관계)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '유리함수의 해석10 (길이와 넓이)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '추론', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '유리함수의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (합성함수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (역함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (합성함수와 역함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (조건항등식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (구간정의함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (Mm, 곡선 위의 점과의 거리)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (Mm, 산술기하)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용8 (정의된 함수)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용9 (함수 구하기)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용10 (격자점의 개수)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용11 (실생활)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용12 (분수방정식 또는 분수부등식)', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '무리식과 무리함수', 12) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '무리식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리식1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리식2 (번분수와 연분수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리식3 (해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이중근호', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '무리함수', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석2 (그래프 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석3 (이동의 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석4 (유리함수 또는 이차함수와 무리함수의 그래프 개형)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석5 (지나는 사분면)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석6 (성질, 합답형)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석7 (함수의 Mm)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석8 (직선과의 위치 관계)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석9 (기타함수 또는 도형과의 위치 관계)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석10 (대소 비교)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '무리함수의 해석11 (길이 또는 넓이)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '무리함수의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (합성함수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (역함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (합성함수와 역함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (증가함수인 원함수와 역함수의 교점)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (증가함수인 원함수 또는 역함수의 위치 관계)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (감소함수인 원함수와 역함수의 교점 및 위치 관계)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (y=x 대칭 활용)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용8 (특수한 형태의 무리함수의 해석)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용9 (특수한 형태의 무리함수의 위치 관계)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용10 (Mm)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용11 (추론과 해석)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용12 (함수 구하기)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용13 (정의된 함수)', 13);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용14 (격자점의 개수)', 14);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용15 (실생활)', 15);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용16 (무리방정식 또는 무리부등식)', 16);
END $$;

COMMIT;
