-- Seed new curriculum subject: 미적분1
-- Run after 01_schema_update.sql and 02_reset_curriculum.sql.

BEGIN;

DO $$
DECLARE
  v_subject_id BIGINT;
  v_major_id BIGINT;
  v_middle_id BIGINT;
BEGIN
  INSERT INTO subjects (name, curriculum_type, order_index) VALUES ('미적분1', 'new', 9) RETURNING id INTO v_subject_id;
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '함수의 극한', 1) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '좌극한과 우극한', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌극한과 우극한1 (그래프 조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌극한과 우극한2 (식 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌극한과 우극한3 (극한값의 존재 조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌극한과 우극한4 (존재성 판단)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌극한과 우극한5 (합성함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌극한과 우극한6 (무한대 관련)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌극한과 우극한7 (추론)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '극한의 성질과 계산', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극한의 성질을 이용한 연산', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형1 (0/0꼴)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형2 (무한대/무한대꼴)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형3 (무한대-무한대꼴)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형4 (무한대X0꼴)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형5 (음의 무한대)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형6 (함수의 극한의 대소 관계)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형7 (부정형과 극한의 성질)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정형8 (활용)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '극한식의 해석', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석1 (미정계수 결정, 0/0꼴)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석2 (미정계수 결정, 기타)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석3 (함수 구하기. 차수 결정)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석4 (함수 구하기. 인수정리)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '해석5 (함수 구하기. 기타)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '극한의 활용', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (좌표와 길이, 넓이)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (원 관련)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (여러가지 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (정의된 함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (진위형)', 5);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '함수의 연속성', 2) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '함수의 연속성', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성1 (구간 표현법)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성2 (연속성 판단)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성3 (연속조건 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성4 (분수식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성5 (구간정의함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성6 (점정의함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성7 (조건항등식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성8 (주기함수)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성9 (함수의 사칙연산)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성10 (합성함수)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '연속성11 (추론과 해석)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '연속함수의 성질과 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '불연속 후보군1 (함수의 합과 차)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '불연속 후보군2 (연속X불연속)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '불연속 후보군3 (불연속X불연속)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '불연속 후보군4 (합성함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '불연속 후보군5 (불연속점의 개수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (교점의 개수로 정의된 함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (기타 정의된 함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (추론)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (진위형)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '사잇값 정리', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대최소정리', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사잇값 정리1 (기본)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사잇값 정리2 (활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '사잇값 정리3 (합답형)', 4);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '미분계수와 도함수', 3) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '미분계수', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분계수1 (평균변화율)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분계수2 (평균변화율과 미분계수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분계수3 (평균변화율과 미분계수의 기하적 의미)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분계수4 (극한식의 해석, 무한소로 갈 때)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분계수5 (극한식의 해석, 특정 값으로 갈 때)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분계수6 (극한식의 해석, 식 변형)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '도함수의 정의와 미분법 공식', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '도함수의 정의', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식1 (공식과 미분계수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식2 (극한식의 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식3 (함수 치환)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식4 (곱의 미분법)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식5 (곱의 미분법, 극한식의 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식6 (적절한 수치대입)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분법 공식7 (시그마로 표현된 함수)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '미분법 공식의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (함수구하기, 인수정리)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (함수구하기, 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (함수구하기, 0의 차수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (몫과 나머지의 해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (조건항등식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (문자 2개 항등식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (조건항등식, 미정계수법)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용8 (부등식의 해석)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '미분가능성과 연속성', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분가능성과 연속성1 (기본판단)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분가능성과 연속성2 (연속성)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분가능성과 연속성3 (극한식의 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분가능조건1 (구간정의함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분가능조건2 (점 정의함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분가능조건3 (곱함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '미분가능조건4 (정의된 함수)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '접선의 방정식', 4) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '접선의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접점1 (접선의 방정식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접점2 (법선의 방정식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '접점3 (해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기울기1 (접선의 방정식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기울기2 (접점의 좌표)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '기울기3 (길이 또는 넓이의 Mm)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선 밖의 점1 (접선의 방정식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '곡선 밖의 점2 (접점의 좌표)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '접선의 방정식의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (접선과 교점의 관계)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (접선에 대한 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (공통접선)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (곡선과 원의 접선)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (함수 구하기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (정의된 함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (추론과 이해)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '평균값의 정리', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '롤의 정리', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균값의 정리1 (기본)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균값의 정리2 (활용)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평균값의 정리3 (부등식의 해석)', 4);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '함수의 증가와 감소', 5) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '함수의 증가와 감소', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소1 (도함수의 의미)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소2 (삼차함수의 증가와 감소)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소3 (삼차함수와 조건 해석, 실수 전체)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소4 (삼차함수와 조건 해석, 제한범위)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '증가와 감소5 (사차함수의 증가와 감소)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '함수의 극대와 극소', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소1 (극대, 극소의 뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소2 (삼차함수의 극대와 극소)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소3 (사차함수의 극대와 극소)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소4 (고차함수의 극대와 극소)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소5 (삼차함수의 극값의 존재성)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소6 (사차함수의 극값의 존재성)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소7 (곱함수와 뺄함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소8 (그래프의 개형)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '극대와 극소9 (다항함수의 계수의 부호)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '증가감소와 극대극소의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (삼차함수의 극값의 차)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (미정계수와 관계식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (구간정의함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (절댓값함수)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (함수 구하기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (추론과 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (정의된 함수)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '함수의 최대와 최소', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대와 최소1 (Mm 구하기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대와 최소2 (함수 구한 후 Mm)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대와 최소3 (Mm 조건 해석)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대와 최소4 (부등식의 해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대와 최소5 (활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대와 최소6 (추론과 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '최대와 최소7 (Mm로 정의된 함수)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '방부등식과 직선운동', 6) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '방정식과 미분', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분1 (삼차방정식의 근의 판별)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분2 (삼차방정식의 실근의 범위)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분3 (사차방정식의 근의 판별)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분4 (다항함수, 방정식의 동치변형)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분5 (변형함수, 방정식의 동치변형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분6 (도함수의 그래프 조건)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분7 (접선의 개수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분8 (정확한 그래프와 실근 추론)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분9 (함수 구하기)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분10 (정의된 함수)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '방정식과 미분11 (추론과 해석)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '부등식과 미분', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분1 (모든 실수)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분2 (제한범위)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분3 (부등식의 동치변형)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분4 (함수구한 후 부등식의 해석)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분5 (함수 구하기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부등식과 미분6 (부등식의 증명)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '속도, 가속도와 미분', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 가속도 (속도와 가속도)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 가속도의 해석1 (주어진 위치함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 가속도의 해석2 (위치함수 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 가속도의 해석3 (두 물체 사이의 거리조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 가속도의 해석4 (운동방향)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 가속도의 해석5 (그래프 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 가속도의 해석6 (실생활)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '변화율1 (길이)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '변화율2 (넓이)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '변화율3 (부피)', 10);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '부정적분', 7) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '부정적분의 뜻', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정적분1 (부정적분의 미분)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정적분2 (부정적분과 미분의 관계)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정적분3 (부정적분으로 정의된 함수)', 3);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '부정적분의 계산', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정적분의 계산1 (기본)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정적분의 계산2 (부정적분의 성질)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정적분의 계산3 (도함수로 표현된 함수의 부정적분)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '부정적분의 계산4 (구간정의함수)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '부정적분의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기1 (조건항등식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기2 (연립항등식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기3 (항등식의 성질)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기4 (미분과 적분)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기5 (곱의 미분법의 역)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기6 (문자 2개 항등식)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '함수 구하기7 (도함수 구하기)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (몫과 나머지의 해석)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (함수의 상황)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (극대와 극소)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (최대와 최소)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (도형 및 실생활)', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '정적분', 8) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분의 계산', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분의 성질1 (기본정리)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분의 성질2 (기본 계산)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분의 성질3 (적분변수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분의 성질4 (적분구간이 같은 경우)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분의 성질5 (피적분함수가 같은 경우)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분의 성질6 (구간정의함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분의 성질7 (절댓값함수)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '계산과 해석1 (정적분 관계식)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '계산과 해석2 (절댓값함수의 해석)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '계산과 해석3 (함수 구하기)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '계산과 해석4 (정의된 함수)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '계산과 해석5 (미지수를 포함한 절댓값함수, 케이스)', 12);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '계산과 해석6 (추론과 해석)', 13);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '여러가지 함수의 정적분', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수의 정적분1 (유함수와 기함수의 계산)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수의 정적분2 (유함수와 기함수의 판단)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수의 정적분3 (대칭성)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수의 정적분4 (평행이동)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수의 정적분5 (주기함수)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '여러가지 함수의 정적분6 (함수 구하기)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분으로 정의된 함수', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분 전체를 치환', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분으로 정의된 함수1 (적분함수)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분으로 정의된 함수2 (피적분함수의 변수와 상수의 구분)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분으로 정의된 함수3 (정적분의 기본정리)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (극한)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (극대와 극소)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (최대와 최소)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (양적관계 활용)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (함수 구하기)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (정의된 함수)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (추론과 해석)', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용8 (실생활)', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '정적분의 활용', 9) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분과 넓이', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이1 (정적분의 기하적 의미)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이2 (그래프 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이3 (그래프 그리기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이4 (포물선의 넓이 공식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이5 (중근관련)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이6 (절댓값함수)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이7 (해석 후 넓이)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이8 (함수결정 후 넓이)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정적분과 넓이9 (곡선과 접선으로 둘러싸인 도형의 넓이)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정적분과 넓이의 해석', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석1 (넓이조건과 관계식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석2 (넓이의 Mm)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석3 (넓이로 정의된 함수)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석4 (넓이가 같을 조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석5 (함수의 대칭성)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '넓이와 해석6 (포함과 배제)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수 관련1 (y축 기준)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수 관련2 (역함수의 정적분)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '역함수 관련3 (원함수와 역함수로 둘러싸인 부분)', 9);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '속도와 거리', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 거리1 (위치, 위치조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 거리2 (속도, 가속도 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 거리3 (이동거리)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 거리4 (그래프)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '속도와 거리5 (실생활)', 5);
END $$;

COMMIT;
