-- Seed new curriculum subject: 기하
-- Run after 01_schema_update.sql and 02_reset_curriculum.sql.

BEGIN;

DO $$
DECLARE
  v_subject_id BIGINT;
  v_major_id BIGINT;
  v_middle_id BIGINT;
BEGIN
  INSERT INTO subjects (name, curriculum_type, order_index) VALUES ('기하', 'new', 12) RETURNING id INTO v_subject_id;
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '포물선', 1) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '포물선의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선의 방정식1 (방정식 세우기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선의 방정식2 (포물선의 방정식 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선의 방정식3 (미정계수 결정)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선의 방정식4 (평행이동과 대칭이동 관련)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '포물선의 정의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용1 (초점, 포물선 위의 점을 이은 선분)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용2 (초점을 지나는 직선)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용3 (삼각형의 무게중심)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용4 (최단거리)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용5 (두 포물선)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용6 (포물선과 원)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용7 (실생활)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자취의 방정식', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선 위의 점의 표현', 9);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '타원', 2) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '타원의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원의 방정식1 (방정식 세우기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원의 방정식2 (타원의 방정식 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원의 방정식3 (미정계수 결정)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원의 방정식4 (평행이동과 대칭이동)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '타원의 정의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용1 (타원의 두 정보)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용2 (타원의 한 정보)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용3 (타원의 X정보)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용4 (둘레의 길이 관련)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용5 (원과 타원)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용6 (포물선과 타원)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용7 (대칭성)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용8 (Mm와 추론)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용9 (실생활)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자취의 방정식', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원 위의 점의 표현', 11);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '쌍곡선', 3) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '쌍곡선의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선의 방정식1 (방정식 세우기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선의 방정식2 (쌍곡선의 방정식 조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선의 방정식3 (미정계수 결정)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선의 방정식4 (평행이동과 대칭이동)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선의 방정식5 (활용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이차곡선 종합', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '쌍곡선의 정의 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용1 (쌍곡선의 두 정보)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용2 (쌍곡선의 한 정보)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용3 (쌍곡선의 X정보)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용4 (둘레의 길이 관련)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용5 (원과 쌍곡선)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용6 (포물선과 쌍곡선)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용7 (타원과 쌍곡선)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용8 (대칭성)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용9 (Mm)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정의 활용10 (실생활)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '자취의 방정식', 11);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선 위의 점의 표현', 12);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '이차곡선과 접선', 4) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '위치 관계', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계1 (포물선과 직선)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계2 (타원과 직선)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계3 (쌍곡선과 직선)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계4 (활용)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '포물선과 접선', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선과 접선1 (접점조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선과 접선2 (접점을 이용한 접선의 성질)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선과 접선3 (기울기조건)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선과 접선4 (길이 또는 넓이의 Mm)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선과 접선5 (곡선 밖의 점)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '포물선과 접선6 (수직조건)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '타원과 접선', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원과 접선1 (접점조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원과 접선2 (기울기조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '타원과 접선3 (길이 또는 넓이의 Mm)', 3);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '쌍곡선과 접선', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선과 접선2 (접점조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선과 접선3 (기울기조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선과 접선4 (길이 또는 넓이의 Mm)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '쌍곡선과 접선5 (곡선 밖의 점)', 4);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '접선의 활용', 5) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (두 개 이상의 이차곡선과 접선의 관계)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (공통접선)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (두 이차곡선의 교점에서의 접선 사이의 관계)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (자취의 방정식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용5 (극선의 방정식)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용6 (빛반사 관련)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용7 (미적분 관련)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '공간도형', 5) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '직선, 평면의 위치관계', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 결정조건', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계1 (직선 또는 평면의 위치 관계)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계2 (두 직선이 이루는 각 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계3 (직선-직선, 직선-평면의 수직)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계4 (합답형 및 증명)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치 관계5 (공간에서의 길이. 넓이. 부피)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '삼수선의 정리', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼수선의 정리1 (기본, 길이)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼수선의 정리2 (길이, 입체도형에 활용)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼수선의 정리3 (넓이와 부피)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼수선의 정리4 (두 직선이 이루는 각의 크기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '삼수선의 정리5 (직선과 평면이 이루는 각)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이면각1 (이면각 구하기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이면각2 (이면각 조건)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '이면각3 (서로 수직인 두 평면)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '정사영', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영1 (기본 공식 적용)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영2 (길이)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영3 (각의 크기 구하기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영4 (이면각이 주어진 경우)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영5 (정사영의 넓이. 이면각이 주어지지 않은 경우)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영6 (처음 도형의 넓이)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영7 (그림자의 넓이)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '공간좌표', 6) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '공간좌표', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '공간좌표1 (공간 위의 점의 좌표)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '공간좌표2 (두 점 사이의 거리)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '공간좌표3 (같은 거리에 있는 점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '공간좌표4 (두 점 사이의 거리의 활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '공간좌표4 (길이합의 Mm)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '정사영', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '선분의 내분점', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분점1 (분점의 좌표)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분점2 (분점의 위치)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분점3 (각의 등분)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분점4 (분점의 사각형에의 활용)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '분점5 (삼각형의 무게중심)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '구의 방정식', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식1 (정의)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식2 (평면 또는 축에 접하는 구의 방정식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식3 (위치 관계)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식4 (현 또는 접선의 길이)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식5 (구와 평면의 교선)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식6 (자취 및 활용)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식7 (Mm)', 7);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '벡터의 연산', 7) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '벡터의 뜻과 연산', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 뜻1 (벡터의 뜻과 크기)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 뜻2 (서로 같은 벡터)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산1 (덧셈과 뺄셈)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산2 (실수배와 연산법칙)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산3 (평면도형에서 벡터의 연산)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산4 (평면도형에서 벡터의 연산과 크기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산5 (공간도형에서 벡터의 연산)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산6 (공간도형에서 벡터의 연산과 크기)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산7 (벡터가 서로 같을 조건)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산8 (벡터의 분할)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 연산9 (실생활)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '벡터의 해석과 활용', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 해석1 (실수배와 평행)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 해석2 (세 점이 한 직선)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 해석3 (벡터방정식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 해석4 (자취)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 해석5 (Mm)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 활용 (이차곡선)', 6);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '위치벡터와 벡터의성분', 8) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '위치벡터', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치벡터1 (위치벡터의 뜻)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치벡터2 (분점벡터)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치벡터3 (무게중심의 위치벡터)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치벡터4 (세 점이 한 직선)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '위치벡터5 (각의 이등분선)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터방정식의 해석1 (벡터의 크기조건 해석)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터방정식의 해석2 (선분 위의 점의 위치 결정)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터방정식의 해석3 (삼각형 외부의 점의 위치 결정)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터방정식의 해석4 (삼각형 내부의 점의 위치 결정)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터방정식의 해석5 (입체도형에서 점의 위치 결정)', 10);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터방정식의 해석6 (자취로 해석)', 11);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '벡터의 성분과 연산', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분1 (성분으로 주어진 평면벡터의 연산)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분2 (성분으로 주어진 평면벡터의 크기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분3 (성분으로 주어진 공간벡터의 연산)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분4 (성분으로 주어진 공간벡터의 크기)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분5 (벡터가 서로 같을 조건)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분6 (벡터를 성분으로 나타내기)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분7 (분점벡터)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분8 (평행)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분9 (벡터방정식의 해석)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '벡터의 성분10 (추론과 해석)', 10);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '벡터의내적', 9) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '벡터의 내적', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적1 (정의)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적2 (내적 구하기, 벡터의 크기 구하기)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적3 (두 벡터가 이루는 각의 크기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적4 (수직조건)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (평면도형)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (공간도형)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (벡터 분할)', 7);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '내적의 성분계산', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '성분과 내적1 (평면벡터의 성분조건)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '성분과 내적2 (공간벡터의 성분조건)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '성분과 내적3 (두 벡터가 이루는 각의 크기)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '성분과 내적4 (평행 또는 수직)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '성분과 내적5 (성분으로 표현)', 5);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '내적의 활용', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용1 (움직이는 점 조건과 자취)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용2 (벡터방정식의 해석)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용3 (원의 벡터방정식. 반지름 표현)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '활용4 (원의 벡터방정식. 지름의 양끝점)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적의 Mm1 (성분이용)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적의 Mm2 (도형)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적의 Mm3 (원의 방정식)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '내적의 Mm4 (벡터의 분할)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '거리의 Mm1 (원의 방정식)', 9);
  INSERT INTO units_major (subject_id, name, order_index) VALUES (v_subject_id, '평면 또는 공간도형의 방정식', 10) RETURNING id INTO v_major_id;
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '좌표평면에서 직선의 방정식', 1) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌표평면1 (방향벡터가 주어진 직선의 방정식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌표평면2 (두 점이 주어진 직선의 방정식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌표평면3 (법선벡터가 주어진 직선의 방정식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌표평면4 (직선의 벡터방정식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 활용1 (두 직선이 이루는 각)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 활용2 (두 직선의 위치 관계)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 활용3 (직선 위의 점의 매개변수 표현)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 활용4 (원과 접선)', 8);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '좌표공간에서 직선의 방정식', 2) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌표공간1 (방향벡터가 주어진 직선의 방정식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌표공간2 (두 점이 주어진 직선의 방정식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '좌표공간3 (직선의 벡터방정식)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 활용1 (두 직선이 이루는 각)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 활용2 (직선 또는 도형의 위치 관계)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '직선의 방정식의 활용3 (직선 위의 점의 매개변수 표현)', 6);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '평면의 방정식', 3) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식1 (법선벡터가 주어진 평면의 방정식)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식2 (직선을 포함하는 평면의 방정식)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용1 (직선과 평면의 교점)', 3);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용2 (두 평면의 교선의 방정식)', 4);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용3 (직선 또는 평면이 이루는 각의 크기)', 5);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용4 (직선 또는 평면의 위치 관계)', 6);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용5 (대칭점)', 7);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용6 (정사영)', 8);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용7 (벡터방정식의 해석)', 9);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '평면의 방정식의 활용8 (점과 평면 사이의 거리)', 10);
  INSERT INTO units_middle (major_unit_id, name, order_index) VALUES (v_major_id, '구의 방정식', 4) RETURNING id INTO v_middle_id;
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식1 (구의 방정식의 벡터 표현)', 1);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식1 (구 또는 평면의 위치 관계)', 2);
  INSERT INTO units_small (middle_unit_id, name, order_index) VALUES (v_middle_id, '구의 방정식2 (두 구의 교선을 포함하는 평면의 방정식)', 3);
END $$;

COMMIT;
